# Site
title: XOXOXOLOLOLOL

# URL
url: https://xoxoxolololol.ml
baseurl: ''

# default url for pages/posts
permalink: :title/

# site directory structure specifications
include: ['_pages']
sass:
  sass_dir: css

# Build settings
markdown: kramdown
port: 4324

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "post"

# Data
social:
  facebook_user: "facebookUserName"
  twitter_user: "nottoopublic"

# Data
social:
  facebook: ""
  instagram: "https://www.instagram.com/missoshiroalgumacoisa/"
  github: ""
  twitter: "https://twitter.com/nottoopublic"
  youtube: ""
  vimeo: ""
  soundcloud: ""
  tumblr: ""
  pinterest: ""
  envelope-o: ""
  twitter_user: "nottoopublic"
